---
title: "Diagnostic Plots - Isokinetic Model"
subtitle: "Within- and between-day test-retest agreement of isometric and isokinetic, multi-joint, upper- and lower-body strength testing"
author: "Michael Nash, James Steele, James P. Fisher"
format:
  pdf:
    documentclass: report
    toc: false
    number-sections: false
    highlight-style: github
    fig-width: 10
    fig-height: 10
---
```{r}
#| message: false
#| warning: false
#| echo: false
#| include: false
targets::tar_config_set(store = here::here('_targets'))
```

# Standardised Mean Difference Model

## Pre-registered Main Model

### $\hat{R}$

```{r}
#| message: false
#| warning: false
#| echo: false

targets::tar_load(isokinetic_model_rhat)

isokinetic_model_rhat 

```

### Trace plots

```{r}
#| message: false
#| warning: false
#| echo: false

targets::tar_load(isokinetic_model_trace)

isokinetic_model_trace

```

### Posterior predictive check

#### Chest Press (Concentric)

```{r}
#| message: false
#| warning: false
#| echo: false

targets::tar_load(isokinetic_model_pp_check_cp_con)

isokinetic_model_pp_check_cp_con

```

#### Leg Press (Concentric)

```{r}
#| message: false
#| warning: false
#| echo: false

targets::tar_load(isokinetic_model_pp_check_lp_con)

isokinetic_model_pp_check_lp_con

```

#### Row (Concentric)

```{r}
#| message: false
#| warning: false
#| echo: false

targets::tar_load(isokinetic_model_pp_check_row_con)

isokinetic_model_pp_check_row_con

```

#### Chest Press (Eccentric)

```{r}
#| message: false
#| warning: false
#| echo: false

targets::tar_load(isokinetic_model_pp_check_cp_ecc)

isokinetic_model_pp_check_cp_ecc

```

#### Leg Press (Eccentric)

```{r}
#| message: false
#| warning: false
#| echo: false

targets::tar_load(isokinetic_model_pp_check_lp_ecc)

isokinetic_model_pp_check_lp_ecc

```

#### Row (Eccentric)

```{r}
#| message: false
#| warning: false
#| echo: false

targets::tar_load(isokinetic_model_pp_check_row_ecc)

isokinetic_model_pp_check_row_ecc

```